# Generated by Django 4.2.11 on 2025-04-06 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_founditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='founditem',
            old_name='date_lost',
            new_name='date_found',
        ),
    ]
