# Generated by Django 4.2.11 on 2025-04-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('driver', 'Driver'), ('passenger', 'Passenger')], default='passenger', max_length=20),
        ),
    ]
